# Generated by Django 2.1 on 2018-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img', models.CharField(max_length=100)),
                ('pid', models.IntegerField(default=1)),
                ('status', models.SmallIntegerField()),
                ('operate_id', models.CharField(max_length=32)),
                ('operate_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='photos',
            old_name='upload_time',
            new_name='operate_time',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='p_img',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='p_name',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='upload_id',
        ),
        migrations.AddField(
            model_name='photos',
            name='desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='photos',
            name='logo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='photos',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='photos',
            name='operate_id',
            field=models.CharField(default='administrator', max_length=32),
        ),
        migrations.AddField(
            model_name='photos',
            name='picture_nums',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.CharField(max_length=150),
        ),
    ]
